### ISSUE TITLE
貌似有BUG

### ISSUE THREAD

**Issue by xykts** [w01230/PCF7953#1]
EPROM  EEPROM数据donwdload进去后 貌似片子没有跑起来 按键下去没有输出  LF部分也没有响应

**Comment by w01230** [comment]
> EPROM EEPROM数据donwdload进去后 貌似片子没有跑起来 按键下去没有输出 LF部分也没有响应

有没有尝试读一下erom 以及eeprom，比较一下数据？
eeprom有效数据多大？ 512B 还是1K？

**Comment by xykts** [comment]
读出来比较是正确的， 不是不编程之后还有特定指令让片子 转入RUN

**Comment by xykts** [comment]
比较了 没错 是不是 烧写进去之后还有特定的指令让芯片进入run模式 能都 qq   328238061------------------ 原始邮件 ------------------发件人: 01230  <notifications@github.com>发送时间: 2018年10月22日 20:38收件人: w01230/PCF7953 <PCF7953@noreply.github.com>抄送: xykts <xykts@163.com>, Author <author@noreply.github.com>主题: 回复：[w01230/PCF7953] 貌似有BUG (#1)
EPROM EEPROM数据donwdload进去后 貌似片子没有跑起来 按键下去没有输出 LF部分也没有响应

有没有尝试读一下erom 以及eeprom，比较一下数据？
eeprom有效数据多大？ 512B 还是1K？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/w01230/PCF7953","title":"w01230/PCF7953","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/w01230/PCF7953"}},"updates":{"snippets":[{"icon":"PERSON","message":"@w01230 in #1: \u003e EPROM EEPROM数据donwdload进去后 貌似片子没有跑起来 按键下去没有输出 LF部分也没有响应\r\n\r\n有没有尝试读一下erom 以及eeprom，比较一下数据？\r\neeprom有效数据多大？ 512B 还是1K？"}],"action":{"name":"View Issue","url":"https://github.com/w01230/PCF7953/issues/1#issuecomment-431823024"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/w01230/PCF7953/issues/1#issuecomment-431823024",
"url": "https://github.com/w01230/PCF7953/issues/1#issuecomment-431823024",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [w01230/PCF7953] 貌似有BUG (#1)",
"sections": [
{
"text": "",
"activityTitle": "**01230**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@w01230",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"w01230/PCF7953\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"w01230/PCF7953\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/w01230/PCF7953/issues/1#issuecomment-431823024"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 398629027\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by w01230** [comment]
那不知道什么原因了。这个程序只负责写验证。你可能需要调试下你的程序。
如果你的EEPROM大于512BYTE 可能有会有问题，512B－1024B 的部分有几个特殊字节没有处理。
不过这应该不影响运行。

**Comment by w01230** [comment]
> 比较了 没错 是不是 烧写进去之后还有特定的指令让芯片进入run模式 能都 

那不知道什么原因了。这个程序只负责写验证。你可能需要调试下你的程序。
如果你的EEPROM大于512BYTE 可能有会有问题，512B－1024B 的部分有几个特殊字节没有处理。
不过这应该不影响运行。

**Comment by w01230** [comment]
close this issue.

**Comment by tusker-tools** [comment]
Hello,
unfortunately I do not speak chinese, but with google translator I think I got the conversation ;-)

Currently I'm focussing exactly the same issue with PCF7945 from BMW remote key. After flashing EROM and EEROM to the chip, I do not get any contact via LF-Field.

Already compared the PCF7945 memory to the dump I programmed: 
- EROM is the same except byte  0x1FFF -->Read only -->  OK
- EEROM is the same except read only bytes --> OK

Seems there is still a small step missing for producing a working PCF. 
Has anybody been able to solve this issue in the meanwhile?

**Comment by w01230** [comment]
> Hello, unfortunately I do not speak chinese, but with google translator I think I got the conversation ;-)
> 
> Currently I'm focussing exactly the same issue with PCF7945 from BMW remote key. After flashing EROM and EEROM to the chip, I do not get any contact via LF-Field.
> 
> Already compared the PCF7945 memory to the dump I programmed:
> 
> * EROM is the same except byte  0x1FFF -->Read only -->  OK
> * EEROM is the same except read only bytes --> OK
> 
> Seems there is still a small step missing for producing a working PCF. Has anybody been able to solve this issue in the meanwhile?

No PCF7953 chip, Items you need check:
You are the 2nd user who report this problem.
1."Boot Routine" is the first program the chip is running and you can check the "Boot Routine" flow in the 7953 spec.
2. You also need to check the "DCFG" in EEPROM bank0 page 127.
3.<img width="883" alt="image" src="https://user-images.githubusercontent.com/1654377/154490702-f2e3a1f8-31c1-411e-b8ae-f2defaaeb736.png">

Then you can feedback here to help other people.

**Comment by tusker-tools** [comment]
**1.** I did a quick test for that: Made a small program which supplies 3.3V to BAT pin, while MSDA and MSDA are tied to GND. PCF should then enter normal boot routine.
**2.** I already checked various times. In the image below you see on the right side the dump which should be programmed to PCF. On the left is what I read back after programming.
![image](https://user-images.githubusercontent.com/82545992/154554268-3c038224-8f95-4152-84df-85d031371881.png)
Byte 1FE and 1FF should be the TMODE bytes in DCFG page. This is 00, which matches the dump. The first two bytes are read-only , should be ok that they differ.

I also tried to set the PCF to protected mode.

Unfortunately nothing did help. Did you manage to bring your PCF back to life (=responding to LF communication)?
I'm very interested in finding the last part of the puzzle. 

**Additional Info:** I am using a 5WK49125 BMW key, which has a PCF7945C05

**Comment by w01230** [comment]
It should worked.  And this was done 4 years ago.
Current I do not have any PCF79xx chip on hand.
By the way if you have NXP programmer on hand. I would suggest do cross test.

**Comment by tusker-tools** [comment]
With which key did you try 4 years ago? Was it a BMW key as well?
Unfortunately I do not have an NXP programmer on hand.

Additional Info: I took my EROM and EEROM from this file [5WK49125](https://transpondery.com/pcf/5WK49125.rar) (pw. "TRANSPONDERY.COM").
 I already tried with two different keys, so I don't think it's an HW defect.
This is a  youtube video of how it should work: [5WK49125 Renew](https://www.youtube.com/watch?v=6VZjC9DV73s&t=71s)

Do you have any idea how I can proceed with debugging the problem?

**Comment by w01230** [comment]
Not BMW key. It's  VOLVO key.
I would suggest  try to check the device mode after power on with EROM&EEROM programmed, then check the  boot routine flow step by step. It may help.
And in the monitor mode it has a C_GO command. You can have a try by modify the code.

**Comment by tusker-tools** [comment]
How can I check the device mode? Do you mean EEDM and EDM (bit 24...27 in EEROM page 127)? This is unfortunately only mentioned in mdi spec, nowhere else. I don't know the meaning of the bits.

I recognized that I made a mistake here:
> **1.** I did a quick test for that: Made a small program which supplies 3.3V to BAT pin, while MSDA and MSDA are tied to GND. PCF should then enter normal boot routine. 

Pulling MSDA to GND during switching on V_BATT is wrong! It should be the other way round: MSDA must not pulled low (=VSS) at power up.
I tried again now with SDA and SCL disconnected from my mikrocontroller (only GND and BATT connected). But I do still not get any LF communication.
Here you see a screenshot of the signals after power-on :
![image](https://user-images.githubusercontent.com/82545992/154860050-59522abd-ceba-455b-865f-1b2e697df367.png)

**Comment by w01230** [comment]
4 years ago.  I do not remember...
For the device mode, you can check the MDI spec via the SDA pin logic level.

**Comment by tusker-tools** [comment]
I tried to set TMODE byte to 0x01 and now I can read at least Hitag2 data. So the transponder is now working via RF.
But unfortuately the BMW specific (extended memory) functionality is not working. Seems that the config on page127 is still not correct.
So my problem is most likely not the programming procedure itself. Maybe this info helps other people trying the same.

**Comment by w01230** [comment]
Thanks for your update~@[usker-tools](https://github.com/tusker-tools)

**Comment by tusker-tools** [comment]
I finally got the key working!!!

The problem was that I used an EROM file where the bit order within each byte was reverted.
In the [PCF File Packet](https://transpondery.com/pcf/5WK49125.rar), you have to use the EROM file in the VVDI folder. This file contains the bytes in the correct order.
Additionally, 5WK45125 BMW key requires the chip to be in protected mode. Only then it is working. In order to achieve this, the command C_PROTECT must be executed after EROM and EEROM were programmed.

**Comment by pyyardyas** [comment]
Hello,
Sorry for reviving the thread but is the PCF7953 datasheet available anywhere? I want to port it to a stm32 but I need to understand the whole logic behind it, thanks

**Comment by tusker-tools** [comment]
> Hello, Sorry for reviving the thread but is the PCF7953 datasheet available anywhere? I want to port it to a stm32 but I need to understand the whole logic behind it, thanks

Hi,
I already ported this to STM32F1. I have a private repository for this. If you are still interested, I will change it to a public repo.

**Comment by pyyardyas** [comment]
What a coincidence haha, I have a STM32F1 on hand, Id be really glad if you could change to public repo.

**Comment by tusker-tools** [comment]
> What a coincidence haha, I have a STM32F1 on hand, Id be really glad if you could change to public repo.

I just changed my repo to public:
https://github.com/tusker-tools/PCF79xx_Tool

I would appreciate your contribution or at least some feedback.
